# Generated by Django 3.2.13 on 2022-05-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_remove_inventory_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(choices=[('TORONTO', 'TORONTO'), ('OTTAWA', 'OTTAWA'), ('KANATA', 'KANATA'), ('NEW YORK', 'NEW YORK'), ('VANCOUVER', 'VANCOUVER')], max_length=50, unique=True),
        ),
    ]
