# Generated by Django 3.2.13 on 2022-05-23 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='city',
        ),
    ]
